FROM ubuntu

RUN apt update
RUN apt -y upgrade
RUN apt install -y git python3 python3-pip git
RUN git clone https://github.com/maxcountryman/flask-login.git
WORKDIR /flask-login
RUN pip install --upgrade pytest
RUN pip install -r requirements/dev.txt
RUN pip install flask-login
